### PR TITLE
Decouple low pass filters of eligibility trace and firing rate

### PR DESCRIPTION
**Pull request by akorgor**
This PR undoes commit https://github.com/JesusEV/nest-simulator/commit/2783bd6bd2f5366f34a3faa9f80957b6879931e0 and aims to fix learning performance issues for the case of `kappa=0`.

### CODE REVIEW

**Comment by JesusEV** [comment]
@akorgor Agnes, there is one technical aspect that is missing. The ideas shown in the lines, `eprop_archiving_node.cpp:213` and, for example, `eprop_iaf.cpp:427` are based on the factorization described in the attached document.
[firing_rate_reg.pdf](https://github.com/user-attachments/files/16886560/firing_rate_reg.pdf)

**Comment by JesusEV** [comment]
@akorgor The sentence "According to Bellec et al. (2020), equation (2) suggests" would be better read as "According to equation (2) from Bellec et al. (2020)".

**Comment by JesusEV** [comment]
@akorgor I can address the missing steps by creating a new branch from this one. Once I'm done, you can merge it back into this branch. Let me know if that works for you.

**Comment by akorgor** [comment]
> @akorgor I can address the missing steps by creating a new branch from this one. Once I'm done, you can merge it back into this branch. Let me know if that works for you.

Ah true, very good point. Please go ahead with the fix!

**Review by JesusEV — APPROVED** [review]

**Pull request merged**
