### PR TITLE
Improved implementation of ptr-to-member-fcn for surrogate gradient

### PR DESCRIPTION
**Pull request by heplesser**
Hi @JesusEV and @akorgor,

This PR cleans up the syntax of the pointer-to-member code by using a typedef (I found https://isocpp.org/wiki/faq/pointers-to-members helpful). Also, the map needs to be created only once as a static variable, not for each call to `select_...()`.

### CODE REVIEW

**Comment by heplesser** [comment]
BTW, do we have tests that check that selecting different surrogate gradient functions works?

**Comment by JesusEV** [comment]
@heplesser Thanks a lot for this elegant approach. A test selecting different surrogate gradients sounds like a nice idea. I will work on that right now and them we can test everything before merging

**Comment by JesusEV** [comment]
This new code passes the tests introduced in [65f6efa](https://github.com/nest/nest-simulator/pull/3207/commits/65f6efa9fc5e7876908f4887fb3145339880de29)

**Comment by akorgor** [comment]
This looks good to me, thanks a lot!

**Review by akorgor — APPROVED** [review]

**Pull request merged**
